"use client";

import { motion } from "framer-motion";
import { useState } from "react";
import Image from "next/image";

// Real texture images generated by AI
const vibeItems = [
    {
        id: 1,
        title: "Concrete",
        subtitle: "Urban Structure",
        image: "/images/texture-concrete.png",
        size: "large",
    },
    {
        id: 2,
        title: "Silk",
        subtitle: "Soft Luxury",
        image: "/images/texture-silk.png",
        size: "small",
    },
    {
        id: 3,
        title: "Midnight",
        subtitle: "After Dark",
        image: "/images/texture-midnight.png",
        size: "small",
    },
    {
        id: 4,
        title: "Golden",
        subtitle: "Warm Tones",
        image: "/images/texture-golden.png",
        size: "medium",
    },
    {
        id: 5,
        title: "Cloud",
        subtitle: "Light & Airy",
        image: "/images/texture-cloud.png",
        size: "medium",
    },
    {
        id: 6,
        title: "Noir",
        subtitle: "Classic Edge",
        image: "/images/texture-noir.png",
        size: "large",
    },
];

const containerVariants = {
    hidden: {},
    visible: {
        transition: {
            staggerChildren: 0.1,
            delayChildren: 0.3,
        },
    },
};

const itemVariants = {
    hidden: {
        opacity: 0,
        y: 30,
        scale: 0.95,
    },
    visible: {
        opacity: 1,
        y: 0,
        scale: 1,
        transition: {
            duration: 0.6,
            ease: [0.16, 1, 0.3, 1] as const,
        },
    },
};

export function IndexGrid() {
    const [hoveredId, setHoveredId] = useState<number | null>(null);

    const getSizeClasses = (size: string) => {
        switch (size) {
            case "large":
                return "col-span-2 row-span-2 aspect-square md:aspect-auto";
            case "medium":
                return "col-span-1 row-span-2 aspect-[3/4]";
            default:
                return "col-span-1 row-span-1 aspect-square";
        }
    };

    return (
        <section className="px-6 md:px-12 py-20 bg-background transition-colors duration-500">
            {/* Section Header */}
            <motion.div
                className="text-center mb-12"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6 }}
            >
                <h2 className="font-display text-2xl md:text-3xl font-bold mb-3">
                    The Index
                </h2>
                <p className="font-body text-foreground/60 max-w-md mx-auto">
                    Shop by mood. Click a vibe to explore.
                </p>
            </motion.div>

            {/* Bento Grid */}
            <motion.div
                className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-6xl mx-auto auto-rows-[150px] md:auto-rows-[180px]"
                variants={containerVariants}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: "-100px" }}
            >
                {vibeItems.map((item) => (
                    <motion.div
                        key={item.id}
                        className={`relative rounded-2xl overflow-hidden cursor-pointer group ${getSizeClasses(
                            item.size
                        )}`}
                        variants={itemVariants}
                        onMouseEnter={() => setHoveredId(item.id)}
                        onMouseLeave={() => setHoveredId(null)}
                        whileHover={{ scale: 1.02 }}
                        transition={{ duration: 0.3 }}
                    >
                        {/* Background Image */}
                        <div className="absolute inset-0 group-hover:scale-110 transition-transform duration-700">
                            <Image
                                src={item.image}
                                alt={item.title}
                                fill
                                className="object-cover"
                            />
                        </div>

                        {/* Overlay */}
                        <div className="absolute inset-0 bg-black/30 group-hover:bg-black/50 transition-colors duration-300" />

                        {/* Content */}
                        <div className="absolute inset-0 flex flex-col items-center justify-center text-white p-4 z-10">
                            <motion.h3
                                className="font-display text-lg md:text-xl font-bold uppercase tracking-wider text-center drop-shadow-md"
                                animate={{
                                    y: hoveredId === item.id ? -5 : 0,
                                }}
                                transition={{ duration: 0.3 }}
                            >
                                {item.title}
                            </motion.h3>
                            <motion.p
                                className="font-body text-xs md:text-sm text-white/90 mt-1 drop-shadow-sm font-medium"
                                initial={{ opacity: 0, y: 10 }}
                                animate={{
                                    opacity: hoveredId === item.id ? 1 : 0,
                                    y: hoveredId === item.id ? 0 : 10,
                                }}
                                transition={{ duration: 0.3 }}
                            >
                                {item.subtitle}
                            </motion.p>
                        </div>

                        {/* Hover Border */}
                        <motion.div
                            className="absolute inset-0 border-2 border-white/0 rounded-2xl z-20"
                            animate={{
                                borderColor:
                                    hoveredId === item.id
                                        ? "rgba(255,255,255,0.5)"
                                        : "rgba(255,255,255,0)",
                            }}
                            transition={{ duration: 0.3 }}
                        />
                    </motion.div>
                ))}
            </motion.div>
        </section>
    );
}
